### ISSUE TITLE
tempfile: command not found

### ISSUE THREAD

**Issue by dimejo** [alphapapa/restic-runner#1]
`/usr/local/bin/restic-runner: line 73: tempfile: command not found`

If I understand correctly the script tries to create a temporary file out of the exclude_file, but the corresponding functions is missing.

**Comment by alphapapa** [comment]
Hi,

What system are you using?  i.e. OS, etc.

**Comment by dimejo** [comment]
OS: CentOS Linux release 7.4.1708 (Core)
Kernel: 3.10.0-693.5.2.el7.x86_64

**Comment by alphapapa** [comment]
Thanks.  I forgot that `tempfile` is specific to Debian.  I'll use `mktemp` instead.
