### ISSUE TITLE
How do I pass this parameter -o b2.connections=50 to the restic-runner script

### ISSUE THREAD

**Issue by sharjeelsayed** [alphapapa/restic-runner#11]
When backing up to backblaze b2 , restic uses the default value of -o b2.connections=5 (https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html ) which makes it pretty slow.It's been recommended to us b2.connections=50 (https://github.com/restic/restic/issues/1383)

e.g. restic -r b2:<bucket_name>:<b2_folder> -o b2.connections=50 backup ~/test_folder

When I try to put this value in the REPONAME file, it throws an error
export RESTIC_REPOSITORY=b2:<bucket_name>:<b2_folder> -o b2.connections=50 

I tried quoting it too but doesn't work.
Is there a way I can pass this value to the restic-runner script?

**Comment by alphapapa** [comment]
There's currently no way to specify arbitrary command line options to the `backup` command.  Here are a few possibilities:

1.  You could use restic-runner's `command` command to specify the Restic backup command manually.   
 This would probably be the easiest thing to do.
2.  You could modify `restic-runner` by inserting the option manually.  Of course, this would make it more difficult to keep up with changes to the script.
3.  You could make a new `restic` script which would be called by `restic-runner`, which would act as a proxy, calling the actual `restic` binary with the additional options.  This would preserve the `restic-runner` script.

**Comment by dimejo** [comment]
You could [connect to B2 with rclone](https://rclone.org/b2/) and see if this speeds things up. rclone can be configured by using environment variables which should be compatible with restic-runners repository configuration.
