### ISSUE TITLE
snapshot-ids does not work

### ISSUE THREAD

**Issue by sharjeelsayed** [alphapapa/restic-runner#12]
This is the output I get when I run snapshot-ids.

`
./restic-runner --repo abcxyz snapshot-ids
`

LOG (2019-03-24 00:21:26): REPO:abcxyz SET: COMMAND:snapshot-ids
LOG (2019-03-24 00:21:58): snapshot-ids FINISHED.  Duration: 32s

**Comment by alphapapa** [comment]
Since, IIRC, you're on Mac, it's probably related to that.  If not, it's probably a configuration problem.

Anyway, it works for me.  You will have to debug the issue.  You've given me nothing to go on, so I can't help you.  Feel free to reopen the issue if you have more information.

**Comment by sharjeelsayed** [comment]
`
./restic-runner --debug --repo abcxyz snapshot-ids
`
DEBUG: ARGS:  --debug --repo 'abcxyz' -- 'snapshot-ids'
DEBUG: Command: snapshot-ids
DEBUG: Rest:
LOG (2019-03-24 17:43:34): REPO:abcxyz SET: COMMAND:snapshot-ids
LOG (2019-03-24 17:44:00): snapshot-ids FINISHED.  Duration: 26s
