### ISSUE TITLE
Accumulating temporary files

### ISSUE THREAD

**Issue by zenofile** [alphapapa/restic-runner#16]
For every `backup` run, the script creates a new temporary file with the specified exclude patterns as its content.

I think the `exclude_file` function is executed in a subshell and the `exclude_file` variable goes out of scope, thus the `cleanup` function actually never gets a valid path to the temporary file.
https://github.com/alphapapa/restic-runner/blob/10dbc57a0c38d2617a3ad1b077f7dce347dd48c0/restic-runner#L253

Modifying `cleanup` to accept the file path as an argument from the trap in `backup` works as expected.

**Comment by alphapapa** [comment]
Thanks for reporting, and for your patience.  This should fix it.
