### ISSUE TITLE
./restic-runner: line 414: readarray: command not found ERROR: Unable to list paths in snapshot

### ISSUE THREAD

**Issue by sharjeelsayed** [alphapapa/restic-runner#26]
I encounter this error 

`./restic-runner: line 414: readarray: command not found ERROR: Unable to list paths in snapshot: <snapshotid>`

while running 

`restic-runner --repo REPONAME --set SETNAME verify-randomly`

I am on macOS Catalina 10.15.7 (19H2) with  GNU bash, version 5.0.18(1)-release (x86_64-apple-darwin19.5.0)

**Comment by alphapapa** [comment]
You may have Bash 5 installed somewhere, but it's probably not the Bash that's being run when you execute this script.  Yet another case of Macs using old Bash versions causing problems.

**Comment by sharjeelsayed** [comment]
No. I am not using the default macOS Bash. I have the latest Bash version installed by Homebrew and that's the one in the path which gets called.

`which bash`
/usr/local/bin/bash

`bash --version`
GNU bash, version 5.0.18(1)-release (x86_64-apple-darwin19.5.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law

**Comment by alphapapa** [comment]
https://github.com/alphapapa/restic-runner/blob/ca6bfcaa912bdb3361bbc68fc6ea0b5cc9b65319/restic-runner#L1
