### ISSUE TITLE
/usr/bin/restic-runner: line 242: -  : syntax error: operand expected (error token is "-  ")

### ISSUE THREAD

**Issue by globalviking** [alphapapa/restic-runner#28]
I'm running Fedora 36 and am trying to run a backup.

I am getting this error.

```
date: invalid date ‘Thu Aug 11 10:30:36 PM -03 2022’
date: invalid date ‘Thu Aug 11 10:30:50 PM -03 2022’
/usr/bin/restic-runner: line 242: -  : syntax error: operand expected (error token is "-  ")

```
The full output is as follows.
```
[i@fedora ~]$ restic-runner --repo amd1 --set sony backup
LOG (2022-08-11 22:30:36): REPO:amd1 SET:sony COMMAND:backup
LOG (2022-08-11 22:30:36): BACKING UP...
repository 2ae84258 opened successfully, password is correct
using parent snapshot 318149f9

Files:           0 new,     0 changed, 15589 unmodified
Dirs:            0 new,     0 changed,  2391 unmodified
Added to the repo: 0 B  

processed 15589 files, 8.556 GiB in 0:08
snapshot 625ad82b saved
date: invalid date ‘Thu Aug 11 10:30:36 PM -03 2022’
date: invalid date ‘Thu Aug 11 10:30:50 PM -03 2022’
/usr/bin/restic-runner: line 242: -  : syntax error: operand expected (error token is "-  ")
LOG (2022-08-11 22:30:50): backup FINISHED.  Duration:  
```
It seems to have worked just fine though. Except for the errors being shown and the duration being blank.

**Comment by alphapapa** [comment]
Hi,

Hm, those "invalid date" lines are unusual and probably point to the problem.  Do you know what's going on there?  Could that be a locale issue?

**Comment by rbnet** [comment]
Same error here in a mixed italian/french locale.
From the Info page for `date` command:

> ...
> 29.1 General date syntax
> ...
>    In the current implementation, only English is supported for words
> and abbreviations like ‘AM’, ‘DST’, ‘EST’, ‘first’, ‘January’, ‘Sunday’,
> ‘tomorrow’, and ‘year’.
> ...

The easiest workaround for me is to add `export LANG=en_EN.utf8` to the script.

**Comment by liloumuloup** [comment]
Hello,

I've got the same bug, and the comment from @rbnet just solved the problem.

Thank you !

**Comment by alphapapa** [comment]
@liloumuloup Thanks for the reminder.

@rbnet Thanks for suggesting the fix.

@globalviking Thanks for reporting.
