### ISSUE TITLE
[RFE] use keep_policy per data set instead of repo

### ISSUE THREAD

**Issue by dimejo** [alphapapa/restic-runner#3]
Currently the keep_policy is defined once per repository. In some cases one might want to apply different policies per data set.

**Comment by alphapapa** [comment]
Hi,

Actually you can do that if you want, just define the variable in the set file instead of the repo file.  I should document that, though.  Thanks.

**Comment by dimejo** [comment]
Great, will try it out. Thanks!

**Comment by alphapapa** [comment]
This is now documented.  Also see the new global config file.  Thanks.  :)
