### ISSUE TITLE
syntax error: operand expected

### ISSUE THREAD

**Issue by dimejo** [alphapapa/restic-runner#4]
OS: CentOS Linux release 7.4.1708 (Core)

```
/usr/local/bin/restic-runner: line 348: -  : syntax error: operand expected (error token is "-  ")
(standard_in) 1: syntax error
/usr/local/bin/restic-runner: line 350: - : syntax error: operand expected (error token is "- ")
date: invalid date ‘Sat  6 Jan 14:57:54 CET 2018’
date: invalid date ‘Sat  6 Jan 15:07:12 CET 2018’
/usr/local/bin/restic-runner: line 124: -  : syntax error: operand expected (error token is "-  ")
```

Please note that due to #1 I was using an [older commit](https://github.com/alphapapa/restic-runner/blob/66918293ea5f8c23f706d9784bf5e8c64b387968/restic-runner), so lines don't match the current master version.

**Comment by alphapapa** [comment]
This is caused by #2.  Maybe we should be more careful about checking whether `du` works.  On the other hand, I'm not sure how complicated I want to make this script.  I'll think about it a bit.  Thanks for reporting.

**Comment by alphapapa** [comment]
I think that should take care of it.  Thanks.
