### ISSUE TITLE
date: illegal time format on MacOS Mojave

### ISSUE THREAD

**Issue by sharjeelsayed** [alphapapa/restic-runner#9]
I get this error when I run in on MacOS Mojave

restic-runner --repo REPONAME init

LOG (2019-03-16 01:55:48): REPO:REPONAME SET: COMMAND:init
LOG (2019-03-16 01:55:48): INITIALIZING...
created restic repository 26b298bd7f at rclone:onedrive:backups

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
restic-runner: line 187: -  : syntax error: operand expected (error token is " ")

**Comment by alphapapa** [comment]
Hello,

Please see https://github.com/alphapapa/restic-runner/pull/5#issuecomment-440976440.  As I don't use MacOS, I can't provide help for it.  I'll add mention of GNU date to the readme.
